services:
  database:
    image: postgres:14.1
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: budgetApp
    volumes:
      - budgetApp:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  budgetApp:
